obj-$(CONFIG_DM_PERSISTENT_DATA) += persistent-data.o
persistent-data-objs := \
	block-manager.o \
	pd-module.o \
	space-map-core.o \
	space-map-disk.o \
	space-map-staged.o \
	space-map-dummy.o \
	transaction-manager.o \
	btree.o \
	btree-remove.o \
	btree-spine.o
